#ifndef LEX_AND_YACC_HEADERS_H
#define LEX_AND_YACC_HEADERS_H
#include "Program.h"
#include "Conditional/IfStmt.h"
#include "StmtList.h"
#include "Conditional/SwitchStmt.h"
#include "Node.h"
#include "Stmt.h"
#include "Conditional/IfStmt.h"
// #include "SubExpr/CondExpr.h"
// #include "SubExpr/ForExpr.h"
// #include "SubExpr/EpsExpr.h"
#include "Loops/For.h"
#include "Loops/While.h"
#include "Loops/DoWhile.h"
#include "expressions/expressions.h"
#include "JmpStmt.h"
#include "Variables/Declaration.h"
#include "Variables/Initialization.h"
#include "Variables/ConstDef.h"
#include "Variables/MultiVarDef.h"
#include "Variables/MultiConstInit.h"
#include "Functions/Function.h"
#endif //LEX_AND_YACC_HEADERS_H
